name: Daily Data Export

on:
  schedule:
    - cron: '30 19 * * *'  # 1AM IST
  workflow_dispatch:         # manual trigger
permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install libraries
        run: |
          pip install s3fs pandas pyarrow

      - name: Run export script
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRECT_KEY}}
        run: python export_data.py

      - name: Push CSV to repo
        run: |
          git config --global user.email "addepallikalyan88@gmail.com"
          git config --global user.name "Kalyan-git-2002"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kalyan-git-2002/logistics_dashboard
          git add *.csv
          git commit -m "Daily refresh $(date)" || echo "No changes"
          git push
